const List<String> kSensorFacts = [
  'Methane formula is CH4.',
  'Methane is the simplest alkane.',
  'Methane contains one carbon atom.',
  'Methane contains four hydrogen atoms.',
  'Methane is colorless gas.',
  'Methane is naturally odorless.',
  'Methane dominates natural gas.',
  'Methane burns with blue flame.',
  'Methane produces carbon dioxide when burned.',
  'Methane is a greenhouse gas.',
  'Methane warms the atmosphere strongly.',
  'Methane lasts about twelve years.',
  'Methane forms in wetlands.',
  'Methane comes from livestock.',
  'Methane leaks from gas pipelines.',
  'Methane exists in coal mines.',
  'Methane was called marsh gas.',
  'Methane liquefies at cryogenic temperatures.',
  'Methane boils near -161.5°C.',
  'Methane helps produce hydrogen.',
  'Methane can produce methanol.',
  'Methane has tetrahedral geometry.',
  'Methane is lighter than air.',
  'Methane is highly flammable.',
  'Methane emissions concern climate scientists.',
  'Ethane formula is C2H6.',
  'Ethane is second-simplest alkane.',
  'Ethane contains two carbon atoms.',
  'Ethane contains six hydrogen atoms.',
  'Ethane is colorless gas.',
  'Ethane is generally odorless.',
  'Ethane belongs to alkanes.',
  'Ethane has one carbon-carbon bond.',
  'Ethane cracks into ethylene.',
  'Ethane helps make polyethylene.',
  'Ethane is petrochemical feedstock.',
  'Ethane occurs in natural gas.',
  'Ethane occurs in petroleum deposits.',
  'Ethane comes from oil refining.',
  'Ethane boils near -88.6°C.',
  'Ethane is highly flammable.',
  'Ethane is a non-polar hydrocarbon.',
  'Ethane has sigma bonds.',
  'Ethane belongs to natural-gas liquids.',
  'Ethane appears in Earth\'s atmosphere.',
  'Ethane influences ozone formation.',
  'Ethane affects methane lifetime.',
  'Ethane is less abundant than methane.',
  'Ethane has staggered conformations.',
  'Ethane rotates around C-C bond.',
];
